version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Mexico_City
    open-pull-requests-limit: 1
    allow:
      - dependency-name: aws-cdk
      - dependency-name: aws-cdk-lib
    groups:
      aws-cdk:
        patterns:
          - aws-cdk
          - aws-cdk-lib

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Mexico_City
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns: ['*']
